"use strict";
const Config={HomeUrl:"browser://start",DefaultWorker:"https://owob-proxy.kkwan812.workers.dev",MaxHistory:200,ZoomLevels:[.5,.67,.75,.8,.9,1,1.1,1.25,1.5,1.75,2],Keys:{Worker:"OwO.ContentWorker",Key:"OwO.ProxyKey",Theme:"OwO.Theme",History:"OwO.History",Bookmarks:"OwO.Bookmarks",OpenTabs:"OwO.OpenTabs",Active:"OwO.ActiveTab"}};
const State={Tabs:[],ActiveId:null,NextId:1,Closed:[]};
const Dom={TabList:document.querySelector("#TabList"),ViewArea:document.querySelector("#ViewArea"),AddressInput:document.querySelector("#AddressInput"),LoadingBar:document.querySelector("#LoadingBar"),Toast:document.querySelector("#Toast"),FindBar:document.querySelector("#FindBar"),FindInput:document.querySelector("#FindInput"),FindStatus:document.querySelector("#FindStatus")};
const load=(k,f)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function ShowToast(t){Dom.Toast.textContent=t;Dom.Toast.classList.add("Show");clearTimeout(ShowToast.t);ShowToast.t=setTimeout(()=>Dom.Toast.classList.remove("Show"),2300)}
function GetWorker(){return String(localStorage.getItem(Config.Keys.Worker)||Config.DefaultWorker).replace(/\/$/,"")}
function GetKey(){return localStorage.getItem(Config.Keys.Key)||""}
function ContentUrl(target){const u=new URL(GetWorker()+"/browse");u.searchParams.set("mode","page");u.searchParams.set("url",target);if(GetKey())u.searchParams.set("key",GetKey());return u.href}
function ResolveInput(v){v=String(v||"").trim();if(!v)return Config.HomeUrl;if(/^browser:\/\//i.test(v))return v.toLowerCase();if(/^https?:\/\//i.test(v))return v;if(/^[\w.-]+\.[a-z]{2,}(?:[\/:?#]|$)/i.test(v))return "https://"+v;return "https://www.bing.com/search?q="+encodeURIComponent(v)}
function Current(){return State.Tabs.find(t=>t.Id===State.ActiveId)}
function GetUrl(t){return t.History[t.Index]||Config.HomeUrl}
function AddHistory(url,title=""){if(!/^https?:/i.test(url))return;const h=load(Config.Keys.History,[]).filter(x=>x.Url!==url);h.unshift({Id:Date.now().toString(36),Url:url,Title:title||url,Time:Date.now()});save(Config.Keys.History,h.slice(0,Config.MaxHistory))}
function SaveTabs(){save(Config.Keys.OpenTabs,State.Tabs.map(t=>({History:t.History,Index:t.Index,Zoom:t.Zoom})));localStorage.setItem(Config.Keys.Active,String(Math.max(0,State.Tabs.findIndex(t=>t.Id===State.ActiveId))))}
function CreateTab(url=Config.HomeUrl,activate=true,data=null){const t={Id:State.NextId++,History:data?.History||[url],Index:data?.Index||0,Zoom:data?.Zoom||1,Title:"新分頁",HasAgent:false};const el=document.createElement("div");el.className="Tab";el.innerHTML='<span class="TabTitle">新分頁</span><button class="TabClose">×</button>';el.onclick=e=>e.target.classList.contains("TabClose")?CloseTab(t.Id):ActivateTab(t.Id);t.TabEl=el;Dom.TabList.append(el);const view=document.createElement("section");view.className="TabView";t.ViewEl=view;Dom.ViewArea.append(view);State.Tabs.push(t);if(activate)ActivateTab(t.Id);Navigate(t,GetUrl(t),false);SaveTabs();return t}
function CloseTab(id){const i=State.Tabs.findIndex(t=>t.Id===id);if(i<0)return;const[t]=State.Tabs.splice(i,1);State.Closed.push({History:t.History,Index:t.Index,Zoom:t.Zoom});t.TabEl.remove();t.ViewEl.remove();if(!State.Tabs.length)CreateTab();else if(State.ActiveId===id)ActivateTab(State.Tabs[Math.max(0,i-1)].Id);SaveTabs()}
function ActivateTab(id){State.ActiveId=id;State.Tabs.forEach(t=>{t.TabEl.classList.toggle("Active",t.Id===id);t.ViewEl.classList.toggle("Active",t.Id===id)});RefreshToolbar()}
function SetTitle(t,title){t.Title=String(title||"網頁").slice(0,120);t.TabEl.querySelector(".TabTitle").textContent=t.Title;t.TabEl.title=t.Title;const h=load(Config.Keys.History,[]);const x=h.find(x=>x.Url===GetUrl(t));if(x){x.Title=t.Title;save(Config.Keys.History,h)}}
function SetLoading(t,on){if(t.Id!==State.ActiveId)return;Dom.LoadingBar.className="LoadingBar "+(on?"Running":"Done")}
function SetContent(t,node,frame=false){t.ViewEl.replaceChildren(node);t.ViewEl.classList.toggle("HasFrame",frame)}
function StartPage(t){SetTitle(t,"新分頁");const w=document.createElement("div");w.className="StartPage";w.innerHTML='<div class="StartLogo"><div class="StartLogoMain">OwO</div><div class="StartLogoSub">Simple Browser</div></div><form class="StartSearch"><span>⌕</span><input placeholder="搜尋或輸入網址"></form><div class="Shortcuts"></div>';w.querySelector("form").onsubmit=e=>{e.preventDefault();Navigate(t,ResolveInput(w.querySelector("input").value))};const items=[["B","Bing","https://www.bing.com"],["G","GitHub","https://github.com"],["W","Wikipedia","https://zh.wikipedia.org"],["R","Reddit","https://www.reddit.com"]];const box=w.querySelector(".Shortcuts");items.forEach(([i,n,u])=>{const b=document.createElement("button");b.className="Shortcut";b.innerHTML=`<span class="ShortcutLetter">${i}</span><span>${n}</span>`;b.onclick=()=>Navigate(t,u);box.append(b)});SetContent(t,w)}
function SettingsPage(t){SetTitle(t,"設定");const w=document.createElement("div");w.className="InternalPage";w.innerHTML='<div class="SettingsHeader"><div class="SettingsHeaderIcon">⚙</div><div><h1>設定</h1><p>OwO Simple Browser</p></div></div><section class="Card"><h2>Cloudflare Worker 內容來源</h2><p class="CardIntro">外部網站使用獨立來源模式載入。</p><label>Worker 根網址</label><input id="WorkerInput" class="SettingInput"><label>存取金鑰（選用）</label><input id="KeyInput" class="SettingInput" type="password"><div class="ButtonRow"><button id="SaveWorker" class="ActionButton">儲存設定</button><button id="ResetWorker" class="ActionButton Secondary">還原預設</button></div></section><section class="Card"><h2>瀏覽資料</h2><div class="ButtonRow"><button id="History" class="ActionButton Secondary">瀏覽紀錄</button><button id="Bookmarks" class="ActionButton Secondary">書籤</button><button id="Clear" class="ActionButton Secondary">清除瀏覽資料</button></div></section>';w.querySelector("#WorkerInput").value=GetWorker();w.querySelector("#KeyInput").value=GetKey();w.querySelector("#SaveWorker").onclick=()=>{const v=w.querySelector("#WorkerInput").value.trim().replace(/\/$/,"");if(!/^https:\/\//i.test(v))return ShowToast("Worker 網址需使用 https://");localStorage.setItem(Config.Keys.Worker,v);localStorage.setItem(Config.Keys.Key,w.querySelector("#KeyInput").value.trim());ShowToast("設定已儲存")};w.querySelector("#ResetWorker").onclick=()=>{localStorage.removeItem(Config.Keys.Worker);localStorage.removeItem(Config.Keys.Key);SettingsPage(t);ShowToast("已還原預設")};w.querySelector("#History").onclick=()=>Navigate(t,"browser://history");w.querySelector("#Bookmarks").onclick=()=>Navigate(t,"browser://bookmarks");w.querySelector("#Clear").onclick=()=>{[Config.Keys.History,Config.Keys.OpenTabs].forEach(k=>localStorage.removeItem(k));ShowToast("已清除瀏覽紀錄與分頁")};SetContent(t,w)}
function ListPage(t,type){const history=type==="history";SetTitle(t,history?"瀏覽紀錄":"書籤");const list=load(history?Config.Keys.History:Config.Keys.Bookmarks,[]);const w=document.createElement("div");w.className="InternalPage";w.innerHTML=`<div class="SettingsHeader"><div class="SettingsHeaderIcon">${history?"◷":"★"}</div><div><h1>${history?"瀏覽紀錄":"書籤"}</h1></div></div><section class="Card"><ul class="ItemList"></ul></section>`;const ul=w.querySelector("ul");if(!list.length)ul.innerHTML='<li class="Empty">目前沒有資料</li>';list.forEach(x=>{const li=document.createElement("li");li.innerHTML=`<a href="#"><span class="ItemTitle"></span><span class="ItemUrl"></span></a><button class="MiniButton">×</button>`;li.querySelector(".ItemTitle").textContent=x.Title||x.Url;li.querySelector(".ItemUrl").textContent=x.Url;li.querySelector("a").onclick=e=>{e.preventDefault();Navigate(t,x.Url)};li.querySelector("button").onclick=()=>{save(history?Config.Keys.History:Config.Keys.Bookmarks,list.filter(y=>y.Id!==x.Id));ListPage(t,type)};ul.append(li)});SetContent(t,w)}
function ExternalPage(t,url){SetTitle(t,"載入中…");SetLoading(t,true);const f=document.createElement("iframe");f.sandbox="allow-scripts allow-same-origin allow-forms allow-modals allow-downloads";f.referrerPolicy="unsafe-url";f.src=ContentUrl(url);f.onload=()=>SetLoading(t,false);SetContent(t,f,true);t.HasAgent=true}
function Navigate(t,url,push=true){url=ResolveInput(url);if(push){t.History=t.History.slice(0,t.Index+1);t.History.push(url);t.Index=t.History.length-1}if(url==="browser://start")StartPage(t);else if(url==="browser://settings")SettingsPage(t);else if(url==="browser://history")ListPage(t,"history");else if(url==="browser://bookmarks")ListPage(t,"bookmarks");else{AddHistory(url);ExternalPage(t,url)}RefreshToolbar();SaveTabs()}
function RefreshToolbar(){const t=Current();if(!t)return;const u=GetUrl(t);Dom.AddressInput.value=u;document.querySelector("#BackButton").disabled=t.Index<=0;document.querySelector("#ForwardButton").disabled=t.Index>=t.History.length-1;document.querySelector("#ZoomButton").textContent=Math.round(t.Zoom*100)+"%";const b=load(Config.Keys.Bookmarks,[]).some(x=>x.Url===u);document.querySelector("#BookmarkButton").textContent=b?"★":"☆";document.querySelector("#BookmarkButton").classList.toggle("Marked",b)}
function ToggleBookmark(){const t=Current(),u=GetUrl(t);if(!/^https?:/i.test(u))return ShowToast("內部頁面不加入書籤");let b=load(Config.Keys.Bookmarks,[]),i=b.findIndex(x=>x.Url===u);if(i>=0){b.splice(i,1);ShowToast("已移除書籤")}else{b.unshift({Id:Date.now().toString(36),Url:u,Title:t.Title||u});ShowToast("已加入書籤")}save(Config.Keys.Bookmarks,b);RefreshToolbar()}
function ChangeZoom(step){const t=Current();if(!t||!t.HasAgent)return;let i=Config.ZoomLevels.findIndex(x=>x>=t.Zoom-.001);i=Math.max(0,Math.min(Config.ZoomLevels.length-1,i+step));t.Zoom=Config.ZoomLevels[i];const f=t.ViewEl.querySelector("iframe");if(f){f.style.transformOrigin="0 0";f.style.transform=`scale(${t.Zoom})`;f.style.width=100/t.Zoom+"%";f.style.height=100/t.Zoom+"%"}RefreshToolbar();SaveTabs()}
function Find(text,back=false){const t=Current(),f=t?.ViewEl.querySelector("iframe");if(!f?.contentWindow)return;f.contentWindow.postMessage({OwOContent:true,Type:"Find",Text:text,Backwards:back},"*")}
window.addEventListener("message",e=>{const d=e.data;if(!d||d.OwOContent!==true)return;const t=Current();if(!t)return;if(d.Type==="Title")SetTitle(t,d.Title);if(d.Type==="Navigate"&&/^https?:/i.test(d.Url))Navigate(t,d.Url);if(d.Type==="OpenTab"&&/^https?:/i.test(d.Url))CreateTab(d.Url);if(d.Type==="Loaded")SetLoading(t,false);if(d.Type==="FindResult")Dom.FindStatus.textContent=d.Count?`${d.Index}/${d.Count}`:"無符合"});
document.querySelector("#AddTabButton").onclick=()=>CreateTab();document.querySelector("#BackButton").onclick=()=>{const t=Current();if(t&&t.Index>0){t.Index--;Navigate(t,GetUrl(t),false)}};document.querySelector("#ForwardButton").onclick=()=>{const t=Current();if(t&&t.Index<t.History.length-1){t.Index++;Navigate(t,GetUrl(t),false)}};document.querySelector("#ReloadButton").onclick=()=>{const t=Current();if(t)Navigate(t,GetUrl(t),false)};document.querySelector("#HomeButton").onclick=()=>Navigate(Current(),Config.HomeUrl);document.querySelector("#SettingsButton").onclick=()=>Navigate(Current(),"browser://settings");document.querySelector("#ThemeButton").onclick=()=>{const dark=document.body.classList.toggle("theme-dark");document.body.classList.toggle("theme-light",!dark);localStorage.setItem(Config.Keys.Theme,dark?"dark":"light")};document.querySelector("#BookmarkButton").onclick=ToggleBookmark;document.querySelector("#ZoomButton").onclick=()=>{const t=Current();if(t){t.Zoom=1;ChangeZoom(0)}};document.querySelector("#AddressForm").onsubmit=e=>{e.preventDefault();Navigate(Current(),Dom.AddressInput.value)};document.querySelector("#FindCloseButton").onclick=()=>Dom.FindBar.hidden=true;document.querySelector("#FindNextButton").onclick=()=>Find(Dom.FindInput.value);document.querySelector("#FindPrevButton").onclick=()=>Find(Dom.FindInput.value,true);Dom.FindInput.oninput=()=>Find(Dom.FindInput.value);document.addEventListener("keydown",e=>{if(e.ctrlKey&&e.key.toLowerCase()==="l"){e.preventDefault();Dom.AddressInput.select()}else if(e.ctrlKey&&e.key.toLowerCase()==="f"){e.preventDefault();Dom.FindBar.hidden=false;Dom.FindInput.focus()}else if(e.ctrlKey&&e.key.toLowerCase()==="d"){e.preventDefault();ToggleBookmark()}else if(e.ctrlKey&&(e.key==="+"||e.key==="=")){e.preventDefault();ChangeZoom(1)}else if(e.ctrlKey&&e.key==="-"){e.preventDefault();ChangeZoom(-1)}else if(e.altKey&&e.key==="ArrowLeft"){e.preventDefault();document.querySelector("#BackButton").click()}else if(e.altKey&&e.key==="ArrowRight"){e.preventDefault();document.querySelector("#ForwardButton").click()}});
document.body.classList.toggle("theme-dark",localStorage.getItem(Config.Keys.Theme)==="dark");document.body.classList.toggle("theme-light",localStorage.getItem(Config.Keys.Theme)!=="dark");const restored=load(Config.Keys.OpenTabs,[]);if(restored.length){restored.forEach((x,i)=>CreateTab(null,i===Number(localStorage.getItem(Config.Keys.Active)||0),x))}else CreateTab();
