"use strict";
const DEFAULT_WORKER="https://owob-proxy.kkwan812.workers.dev";
const HOME="browser://start";
const S={tabs:[],active:null,next:1};
const E={tabs:document.querySelector("#tabs"),views:document.querySelector("#views"),address:document.querySelector("#address"),progress:document.querySelector("#progress"),toast:document.querySelector("#toast")};
const workerBase=()=>String(localStorage.getItem("OwO.ContentWorker")||DEFAULT_WORKER).replace(/\/$/,"");
const workerKey=()=>localStorage.getItem("OwO.ProxyKey")||"";
function contentUrl(target,mode="page"){const u=new URL(workerBase()+"/browse");u.searchParams.set("mode",mode);u.searchParams.set("url",target);if(workerKey())u.searchParams.set("key",workerKey());return u.href}
function resolveInput(v){v=String(v||"").trim();if(!v)return HOME;if(/^browser:\/\//i.test(v))return v.toLowerCase();if(/^https?:\/\//i.test(v))return v;if(/^[\w.-]+\.[a-z]{2,}(?:[\/:?#]|$)/i.test(v))return "https://"+v;return "https://www.bing.com/search?q="+encodeURIComponent(v)}
function toast(t){E.toast.textContent=t;E.toast.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>E.toast.classList.remove("show"),2200)}
function current(){return S.tabs.find(t=>t.id===S.active)}
function createTab(url=HOME){const t={id:S.next++,history:[url],index:0,title:"新分頁",loading:false};S.tabs.push(t);const b=document.createElement("button");b.className="tab";b.innerHTML='<span class="tab-title">新分頁</span><span class="tab-close">×</span>';b.onclick=e=>{if(e.target.classList.contains("tab-close"))closeTab(t.id);else activate(t.id)};t.button=b;E.tabs.appendChild(b);const v=document.createElement("section");v.className="view";t.view=v;E.views.appendChild(v);activate(t.id);navigate(t,url,false);return t}
function closeTab(id){const i=S.tabs.findIndex(t=>t.id===id);if(i<0)return;const [t]=S.tabs.splice(i,1);t.button.remove();t.view.remove();if(!S.tabs.length)return createTab();if(S.active===id)activate(S.tabs[Math.max(0,i-1)].id)}
function activate(id){S.active=id;S.tabs.forEach(t=>{t.button.classList.toggle("active",t.id===id);t.view.classList.toggle("active",t.id===id)});refresh()}
function setTitle(t,title){t.title=String(title||"網頁").slice(0,120);t.button.querySelector(".tab-title").textContent=t.title}
function loading(t,on){t.loading=on;if(t.id===S.active){E.progress.className="progress "+(on?"on":"done")}}
function renderStart(t){setTitle(t,"新分頁");t.view.innerHTML='<div class="start"><div class="card"><h1 class="logo">OwO</h1><h2>Simple Browser</h2><p class="hint">GitHub Pages ＋ Cloudflare Worker 獨立內容來源模式</p><form class="search"><input placeholder="搜尋或輸入網址"><button>前往</button></form></div></div>';t.view.querySelector("form").onsubmit=e=>{e.preventDefault();navigate(t,resolveInput(t.view.querySelector("input").value))}}
function renderSettings(t){setTitle(t,"設定");t.view.innerHTML='<div class="settings-page"><div class="card"><h1>設定</h1><p class="hint">Cloudflare Worker 內容來源</p><input class="setting-input" id="worker" placeholder="https://xxx.workers.dev"><p class="hint">存取金鑰（選用）</p><input class="setting-input" id="key" type="password"><p><button class="primary" id="save">儲存</button></p><p class="hint">外部頁面改用 iframe.src，內容與 GitHub Pages 主介面保持不同來源。</p></div></div>';t.view.querySelector("#worker").value=workerBase();t.view.querySelector("#key").value=workerKey();t.view.querySelector("#save").onclick=()=>{const w=t.view.querySelector("#worker").value.trim().replace(/\/$/,"");if(!/^https:\/\//i.test(w))return toast("Worker 網址需使用 https://");localStorage.setItem("OwO.ContentWorker",w);localStorage.setItem("OwO.ProxyKey",t.view.querySelector("#key").value.trim());toast("設定已儲存")}}
function renderExternal(t,url){loading(t,true);setTitle(t,"載入中…");const f=document.createElement("iframe");f.sandbox="allow-scripts allow-same-origin allow-forms allow-modals allow-downloads allow-popups-to-escape-sandbox";f.referrerPolicy="no-referrer";f.src=contentUrl(url,"page");f.onload=()=>loading(t,false);t.view.replaceChildren(f)}
function navigate(t,url,push=true){url=resolveInput(url);if(push){t.history=t.history.slice(0,t.index+1);t.history.push(url);t.index=t.history.length-1}if(url==="browser://start")renderStart(t);else if(url==="browser://settings")renderSettings(t);else renderExternal(t,url);refresh()}
function refresh(){const t=current();if(!t)return;const u=t.history[t.index];E.address.value=u;document.querySelector("#back").disabled=t.index<=0;document.querySelector("#forward").disabled=t.index>=t.history.length-1}
window.addEventListener("message",e=>{const d=e.data;if(!d||d.OwOContent!==true)return;const t=current();if(!t)return;if(d.Type==="Title")setTitle(t,d.Title);if(d.Type==="Navigate"&&/^https?:\/\//i.test(d.Url))navigate(t,d.Url);if(d.Type==="OpenTab"&&/^https?:\/\//i.test(d.Url))createTab(d.Url);if(d.Type==="Location"&&/^https?:\/\//i.test(d.Url)){t.history[t.index]=d.Url;refresh()}if(d.Type==="Loaded")loading(t,false)});
document.querySelector("#newTab").onclick=()=>createTab();document.querySelector("#back").onclick=()=>{const t=current();if(t&&t.index>0){t.index--;navigate(t,t.history[t.index],false)}};document.querySelector("#forward").onclick=()=>{const t=current();if(t&&t.index<t.history.length-1){t.index++;navigate(t,t.history[t.index],false)}};document.querySelector("#reload").onclick=()=>{const t=current();if(t)navigate(t,t.history[t.index],false)};document.querySelector("#home").onclick=()=>navigate(current(),HOME);document.querySelector("#settings").onclick=()=>navigate(current(),"browser://settings");document.querySelector("#addressForm").onsubmit=e=>{e.preventDefault();navigate(current(),E.address.value)};
createTab();
